package com.BeagleBinary.Models;


import com.BeagleBinary.Repositories.SensorDataRepository;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.ArrayList;
import java.util.List;

@DynamoDBDocument
@DynamoDBTable(tableName = "Sensor")
public class SensorModel {

    @Autowired
    private SensorDataRepository sensorDataRepository;
    private String id;
    private String userId;
    private String externalAddress;


    public SensorModel(){}


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }


    public void setId(String id){
        this.id = id;
    }


    @DynamoDBAttribute
    public String getUserId()
    {
        return this.userId;
    }


    public void setUserId(String userId)
    {
        this.userId = userId;
    }

    @DynamoDBAttribute
    public String getExternalAddress()
    {
        return this.externalAddress;
    }


    public void setExternalAddress(String address)
    {
        this.externalAddress = address;
    }


    public void deleteSensorData(String dataId){
        System.out.println("DELETING SENSOR TAG NOT DONE");
    }
}
