package com.BeagleBinary.Models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.ArrayList;
import java.util.List;
@DynamoDBDocument
@DynamoDBTable(tableName = "User")
public class UserModel {
    private String id;
    private String userName;
    private String firstName;
    private String lastName;
    private String emailAddress;
    private String phoneNumber;
    private String password;
    private String deviceIdString;

    private List<String> deviceIds;


    public UserModel()
    {
        userName = "";
        firstName= "";
        lastName= "";
        emailAddress= "";
        phoneNumber= "";
        password= "";
    }

    public UserModel(String userName, String firstName, String lastName, String emailAddress,
                     String phoneNumber, String password)
    {
        this.userName = userName;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddress = emailAddress;
        this.phoneNumber = phoneNumber;
        this.password = password;
        this.deviceIdString = "";
    }


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getUserName() {
        return this.userName;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return this.firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return this.lastName;
    }

    @DynamoDBAttribute
    public String getEmailAddress() { return this.emailAddress; }

    @DynamoDBAttribute
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    @DynamoDBAttribute
    public String getPassword() {
        return this.password;
    }

    @DynamoDBAttribute
    public String getDeviceIdString() {
        return this.deviceIdString;
    }


    public void setId(String id){
        this.id = id;
    }


    public void setUserName(String userName) {
        this.userName = userName;
    }


    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }


    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


    public void setPassword(String password) {
        this.password = password;
    }


    public void setDeviceIdString(String deviceId)
    {

        if(deviceIds == null)
        {
            deviceIds = new ArrayList<String>();
        }

        deviceIds.add(deviceId);
        deviceIdString = deviceIds.toString();
    }


}
